# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 13:16
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0002_logentry_remove_auto_add'),
        ('boxer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='All bids are final. Price in US dollars.', max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to=b'')),
                ('delivery_code', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('region', models.CharField(max_length=64)),
                ('zipcode', models.CharField(max_length=10)),
                ('phone', localflavor.us.models.PhoneNumberField(max_length=20)),
                ('ranking', models.IntegerField()),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to=b'')),
                ('side', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('schedule_detail', models.CharField(blank=True, max_length=100)),
                ('payment_detail', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(help_text='Format (Hour & Minute are optional): 10/25/2006 14:30')),
                ('end_time', models.DateTimeField(help_text='Format (Hour & Minute are optional): 10/25/2006 14:30')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='auctionevent',
            name='item',
        ),
        migrations.RemoveField(
            model_name='auctionevent',
            name='winning_bidder',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='auction_event',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.DeleteModel(
            name='Freighter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='auction_event',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='departure',
        ),
        migrations.AddField(
            model_name='delivery',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='arrival_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='arrival_lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='delivery',
            name='departure_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='departure_lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='in_auction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='delivery',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='freighter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_freighter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AuctionEvent',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='schedule',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_events', to='boxer.Delivery'),
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_delivery', to='boxer.Delivery'),
        ),
    ]
