# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxer', '0002_auto_20171107_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='freighter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_freighter', to=settings.AUTH_USER_MODEL),
        ),
    ]
