# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxer', '0003_auto_20171107_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
