# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freighter', models.IntegerField()),
                ('departure', models.CharField(max_length=256)),
                ('arrival', models.CharField(max_length=256)),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('volume', models.FloatField()),
                ('weight', models.FloatField()),
                ('image', models.ImageField(max_length=128, upload_to=b'')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Freighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=64)),
            ],
        ),
    ]
